#' Area-based clear cuts
#'
#' Selects cells for clear cuts on an area-based
#' 
#' @param land A \code{landscape} data frame with forest stand records in rows
#' @param params A list of default parameters generated by the function \code{default.params()} ora customized list of model parameters
#' @param is.harvprem A flag to indicate if premature harvesting is allowed
#' 
#' @return A list of four items: 
#'  \itemize{
#'  \item{\code{cc.cells}: A vector with the \code{cell.id} of the clear cut cells}
#'  \item{\code{pc.cells}: A vector with the \code{cell.id} of the partial cut cells}
#'  \item{\code{track.cut}: A data frame with managed areas by different prescriptions}
#'  \item{\code{spp.track}: A data frame with the area and volume clear-cut and partial cut per species}
#'  }
#' 
#' @export
#' 
#' @examples
#' source("R/default.params.r")
#' params = default.params()
#' load("data/landscape.rda")
#' harvest = harvest.area(landscape, params, is.harvprem=F) 

harvest.area = function(land, params, is.harvprem=F){
  
  #1. Management units
  land2 = land[!is.na(land$mgmt.unit) & !land$spp=="NonFor" & !land$mgmt.unit=="AGNA",] #AGNA out of management. This implies harvesting and later Artificial planting.
  units = as.character(sort(unique(land2$mgmt.unit[!is.na(land2$mgmt.unit)])))
  units = units[-which(units == c("AGNA"))]

  #2. Harvestable cells
  if(is.harvprem){
    land.inc = filter(land2, !is.na(mgmt.unit) & is.na(exclus) & age>(age.matu-20) & spp!=("ERS"))
  } else{
    land.inc = filter(land2, !is.na(mgmt.unit) & is.na(exclus) & age>age.matu & spp!=("ERS"))
  } #*is ERS the only species excluded?
  
  
  #3. Select number of cells to harvest
  ##Forest
  land.num = filter(land2, !is.na(mgmt.unit) & is.na(exclus) & spp!=("ERS"))

  ## Number of harvest cells according to the scenario
  hr = params$harv.rate     #as.numeric(tbls$scn.df[tbls$scn.df$ScnName==scn, 2])  = HarvRate
  n_hr = round(hr*nrow(land.num))
  
  #4. Select cells to harvest
  ## Select the %(=hr) of cells for each unit mgmt
  if (nrow(land.inc)>n_hr)
  { selection = land.inc %>% group_by(mgmt.unit) %>% 
    sample_n(size = round(n_hr * n() / nrow(land.inc)), replace = F) %>% 
    ungroup() %>% slice_sample(n = n_hr)
    
    cc.cells = selection$cell.id}
  else
  {selection = data.frame(var1 = character())
    cc.cells = 0}

  
  #5. Track and return  
  return(selection)
  
}

