#' Area-based clear cuts
#'
#' Selects cells for clear cuts on an area-based
#' 
#' @param land A \code{landscape} data frame with forest stand records in rows
#' @param params A list of default parameters generated by the function \code{default.params()} or 
#' a customized list of model parameters
#' @param scn A character indicating the type of transition according artificial planting scenario: \code{A} for "scn1", etc.
#' @param tbls A list of default input tables as in \code{data(default.tables()} or a customized list of input tables
#' 
#' @return A list of four items: 
#'  \itemize{
#'  \item{\code{cc.cells}: A vector with the \code{cell.id} of the clear cut cells}
#'  \item{\code{pc.cells}: A vector with the \code{cell.id} of the partial cut cells}
#'  \item{\code{track.cut}: A data frame with managed areas by different prescriptions}
#'  \item{\code{spp.track}: A data frame with the area and volume clear-cut and partial cut per species}
#'  }
#' 
#' @export
#' 
#' @examples
#' source("R/default.params.r");params = default.params()
#' load("data/landscape.rda")
#' load("data/default.tables.rda")
#' harvest = harvest.area(landscape, params, default.tables, scn="scn1", is.harvloc=F, is.harvprem=F) 
#' 
#' land=landscape; params=default.params(); tbls=default.tables; scn="scn1"

harvest.area<-function(land, params, tbls, scn, is.harvloc,is.harvprem){
  
  #1. Management units
  land2 <- land[!is.na(land$mgmt.unit) & !land$spp=="NonFor" & !land$mgmt.unit=="AGNA",] #AGNA out of management. This implies harvesting and later Artificial planting.
  units <- as.character(sort(unique(land2$mgmt.unit[!is.na(land2$mgmt.unit)])))
  units <- units[-which(units == c("AGNA"))]
  
  #2. Harvestable cells
  if (is.harvprem)
  {land.inc <- filter(land2, !is.na(mgmt.unit) & is.na(exclus) & age>(age.matu-20) & spp!=("ERS"))}
  else
  {land.inc <- filter(land2, !is.na(mgmt.unit) & is.na(exclus) & age>age.matu & spp!=("ERS"))} #*is ERS the only species excluded?
  
  
  #3. Select number of cells to harvest
  ##Forest
  land.num <- filter(land2, !is.na(mgmt.unit) & is.na(exclus) & spp!=("ERS"))
  
  ## Number of harvest cells according to the scenario
  hr <- as.numeric(tbls$scn.df[tbls$scn.df$ScnName==scn,2])
  n_hr <- round(hr*nrow(land.num))
  
  
  #4. Select cells to harvest
  ## Select the %(=hr) of cells for each unit mgmt
  if (nrow(land.inc)>n_hr)
  { selection <- land.inc %>% group_by(mgmt.unit) %>% 
    sample_n(size = round(n_hr * n() / nrow(land.inc)), replace = F) %>% 
    ungroup() %>% slice_sample(n = n_hr)
    
    cc.cells <- selection$cell.id}
  else
  {selection = data.frame(var1 = character())
    cc.cells <- 0}

  
  #5. Track and return  
  return(selection)
  
}

